config/routes.rb
Rails.application.routes.draw do
  root "boards#index"

  resources :boards, shallow: true do
    post :star_board, to: 'boards#star'
    resources :lists, only: [:new, :create, :destroy] do
      collection do
        patch :sortlist
      end
    end
    member  do
      post :searchuser
    end
    collection do
      put :agree_invite
    end
  end

  scope :lists do
    resources :cards, except: [:index, :new, :edit] do
      resources :comments, only: [:create, :destroy]
      member do
        put :assign
        put :tagging  
      end  
      collection do
        patch :sortcard
      end
    end
  end 

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
end

app/views/shared/_boardheader.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light py-0 py-md-0">

  <h2 class="board-inside-title mt-2"><%= @board.title %></h2>
<!-- Board archived  -->
  <div class="nav-item active starred-board" data-controller="star" data-star-id="<%= @board.id %>">
    <a href="" class="btn btn-lg btn-bh" data-action="star#toggle">
      <% if @board.starred_by?(current_user) %>
        <i class="fas fa-star" data-target="star.icon"></i>
      <% else %>
        <i class="far fa-star" data-target="star.icon"></i>
      <% end %>
    </a>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
<!-- Board Visibility  -->
      <li class="nav-item dropdown btn btn-bh ml-2 btn-light">
        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= @board.visibility %>
        </a>
        <%# <div class="dropdown-menu" 
        aria-labelledby="navbarDropdown">
          <div class="dropdown-item">
            <div>狀態</div>
          <div class="dropdown-divider"></div>
            <div>stsr:收藏於我的最愛</div>
            <div>私人:</div>
            <div>團隊:</div>
          </div> %>
      </li>
<!-- Board member list  -->
      <li class="nav-item dropdown btn btn-bh ml-2 btn-light">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          團員
        </a>
        <ul class="dropdown-menu scrollable_menu" aria-labelledby="dropdownMenuOffset">
          <% @board.users.each do |member| %>
            <li class="dropdown-item">
              <span>
                <% if member.avatar.attached? %>
                  <%= image_tag member.avatar.variant(resize_to_limit: [48, 48]),height:48, width:48, class: 'rounded-circle mr-2' %>
                <% else %>
                  <%= image_tag "user avatar default.png", height:48, width:48, class: 'rounded-circle clickhand mr-2' %>
                 <% end %>
                <%= member.username %>
              </span>
            </li>
          <% end %>
        </ul>
      </li>
<!-- Form for Invitation to other users -->
      <li class="nav-item dropdown btn btn-bh ml-2 btn-light">
        <a class="nav-link dropdown-toggle invite_controller" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          邀請
        </a>
        <div class="dropdown-menu dropdown_menu_add dropdown_menu_size" 
        aria-labelledby="navbarDropdown">
          <div class="p-2">
            <div class="text-info">
              <i class="far fa-paper-plane m-2 text-info d-inline-flex"></i>
              <p class=" d-inline-flex">寄送邀請訊息</p>
                <%=  form_with scope: :search, url: searchuser_board_path do |f| %>
              <div class="form-group">
                <%= f.text_field :email, class:"form-control", id: "navbarDropdown_email", placeholder:"請輸入Email" %>
              </div>
              <div class="form-group">
                <%= f.text_area :message, class:"form-control", id: "navbarDropdown_message", placeholder:"邀請內容..." %>
              </div>
              <%= f.submit "送出邀請", class:"btn btn-sm btn-info" %>
              <% end %>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg my_navbarset py-0 justify-content-end" id="navbar" >
  <div id="main_navbar">

    <%= link_to root_path, class:"navbar_btn_bgc navbar_logo_place mx-auto" do %>
      <%= image_tag "smashmello-logo-2-white(default)(navbar).png", alt: "Smashmello", height:38, width:128 %>
    <% end %>

    <div class="dropdown mr-auto">
      <% if user_signed_in? %>
        <span id="navbar_user_Dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar.variant(resize_to_limit: [48, 48]),height:38, width:48, class: 'rounded-circle btn-sm navbar_btn_bgc clickhand' %>
          <% else %>
            <%= image_tag "user avatar default.png", height:38, width:38, class: 'rounded-circle clickhand' %>
          <% end %>
        </span>
        <div class="dropdown-menu user_dropdown_menu_size dropdown-menu-right" aria-labelledby="navbar_user_Dropdown">
          <div class="username"></div>
            <div class="mx-2 text_wrap">
              <i class="fas fa-user ml-2 mt-1"></i>
                <%= current_user.username %>
          </div>
          <div class="dropdown-divider"></div>
          <div class="useremail d-inline-flex">
            <div class="mx-2 text_wrap">
              <i class="fas fa-envelope ml-2 mt-1"></i>
                <%= current_user.email %>
            </div>
          </div> 
          
          <div class="dropdown-divider"></div>
          <%= link_to "使用者設定", edit_user_registration_path, class: 'dropdown-item btn-info' %>
          <div class="dropdown-divider"></div>
          <%= link_to destroy_user_session_path, method: "delete", data: {confirm: "要登出嘛"} , class: 'dropdown-item btn-info' do %>
            登出　<i class="fas fa-sign-out-alt"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</nav>