config/routes.rb
Rails.application.routes.draw do
  root "boards#index"

  resources :boards, shallow: true do
    post :star_board, to: 'boards#star'
    resources :lists, only: [:new, :create, :destroy] do
      collection do
        patch :sortlist
      end
    end
    member  do
      post :searchuser
    end
    collection do
      put :agree_invite
    end
  end

  scope :lists do
    resources :cards, except: [:index, :new, :edit] do
      resources :comments, only: [:create, :destroy]
      member do
        put :assign
        put :tagging  
      end  
      collection do
        patch :sortcard
      end
    end
  end 

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, :visibility, presence: true

  has_many :lists
  has_many :cards
  
  has_many :user_boards
  has_many :users, through: :user_boards

  has_many :star_boards
  has_many :starred_boards, through: :star_boards, source: :user

  has_many :board_messages, inverse_of: :board

  has_many :search_users

  def starred_by?(user)
    star_boards.exists?(user: user)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  layout "board", :only => :index
  before_action :find_board, only: [:edit, :update, :destroy, :show, :searchuser]
  before_action :search_params, only: [:searchuser]

  def index
    @boards = current_user.boards.all
    @board = Board.new()
    @private_boards = current_user.boards.where(visibility: "私人")
    @public_boards = current_user.boards.where(visibility: "團隊")
    @star_boards = current_user.starred_boards.all
    @searchuser = current_user.search_users.all
  end

  def show
    @lists = @board.lists.sorted.includes(:cards)
    @list = List.new()
  end

  def create
    board = current_user.boards.create(board_params)
    redirect_to board_path(board.id), notice: "新增成功!" unless board.blank?
  end

  def update
    if @board.update_attributes(board_params)
      redirect_to boards_path, notice: "資料更新成功!"
    else
      render :edit
    end
  end

  def star
    board = Board.find(params[:board_id])
    star = StarBoard.find_by(user: current_user, board: board)
    starred = false

    if star
      star.destroy
      starred = false
    else
      current_user.star_boards.create(board: board)
      starred = true
    end
    render json: {status: 'ok', starred: starred}
  end

  def destroy
    current_user.boards.destroy(find_board)
    redirect_to boards_path, notice: "已刪除!"
  end

  def searchuser
    user = User.find_by(email: @email)
    if user.blank?
      render :js => "alert('沒有這位使用者，請重新輸入')"
    else
      if @board.user_ids.include?(user.id) == false 
        invitation = SearchUser.create(user: user,
                                        board: @board,
                                        email: @email, 
                                        message: @message)
       ActionCable.server.broadcast "notifications:#{user.id}", invitation
     else
      render :js => "alert('使用者已加入此表單，請重新輸入')"
     end
    end
    respond_to do |format|
      format.js
    end
  end

  def agree_invite 
    invitation = SearchUser.find(params[:id])
    reply = params[:agree] 
    board = Board.find(params[:board_id])
    if reply == "true"
      board.users << [current_user]
      board.update(visibility: "團隊")
      invitation.destroy
    else
      invitation.destroy
    end
    respond_to do |form|
      form.js
    end
  end
  
  private
  def board_params
    params.require(:board).permit(:title, :visibility)
  end

  def search_params
    @email = params.dig(:search, :email)
    @message = params.dig(:search, :message)
  end

  def find_board
    @board = Board.find(params[:id])
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_boardcreate.html.erb
<div class="modal fade" id="createBoard" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content col mt-5 p-5 text-info">
      <h2 class="mb-4">新增看板</h2>
      <%= form_for board do |board| %>
        <div class="form-group">
          <%= board.label :title, "標題" %>
          <%= board.text_field :title , class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= board.label :visibility, "狀態" %>
          <%= board.select :visibility, options_for_select(['私人']) %>
        </div>
        <div class="form-group d-flex justify-content-end">
          <%= board.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/_carditem.html.erb
<div class="modal fade" id="Carditem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content col pt-3 px-1 text-secondary overview">
      <div class="container">
        <div class="row">
          <div class="card-head col-12">
            <i class="far fa-window-maximize fa-lg"></i>
            <h5 data-role="card-inner_title" id="card-title" class="d-inline-block mb-3 font-weight-bold text-dark"
              contenteditable="true"></h5>
            <span class="picked-date"></span>
            <span data-role="card-focus-id" class="d-none"></span>
          </div>
        </div>

        <!-- Card assignee & tags -->
        <div class="row">
          <div class="col-9">
            <div class="card-detail">
              <p class="p-tag-list">標籤:</p>
              <div class="tag-list"></div>
              <p class="p-card-member">成員:</p>
              <div class="card-member"></div>
            </div>

            <!-- Card description -->
            <div class="form-group my-2">
              <div class="description-title mb-1">
                <i class="fas fa-align-left"></i>
                <label class="desc-header ml-1" for="card-description">內容</label>
              </div>
              <textarea data-role="card-description" id="card-description" class="form-control"
                placeholder="加入更多細節..."></textarea>
            </div>

            <!-- Comment text -->
            <div class="form-group my-2">
              <div class="comment-title mt-3 mb-1">
                <i class="far fa-comment-alt"></i>
                <label class="comment-header ml-1" for="card-comment">留言</label>
              </div>
              <textarea data-role="comment-input" id="card-comment" class="form-control"
                placeholder="留下訊息..."></textarea>
              <button data-role="comment-send" id="comment-send" type="submit"
                class="btn btn-sm btn-success mt-1">送出</button>
            </div>
            <!-- Comment area -->
            <div data-role="comment-area">
              <!-- Comment list -->
              <div class="comment-container">
                <div class="comment-header">
                  <span class="author"></span>
                  <span class="comment-time"></span>
                </div>
                <div class="comment-body">
                </div>
              </div>

            </div>
          </div>

          <!-- Side Bar -->
          <div class="col-3">
            <span class="add-to">加入至卡片</span>

            <!-- Assign member -->
            <div class="dropdown mr-1">
              <label class="assign btn btn-light my-1" id="dLabel" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                <span><i class="fas fa-user-friends fa-sm"></i></span>
                <span class="member-title">成員</span>
              </label>
              <ul class="member-menu dropdown-menu" aria-labelledby="dropdownMenuOffset">
                <% @board.users.each do |member| %>
                <li class="member-list dropdown-item">                
                  <span class="member" data-memberId="<%= member.id %>">
                    <% if member.avatar.attached? %>
                      <%= image_tag member.avatar.variant(resize_to_limit: [48, 48]),height:48, width:48, class: 'rounded-circle mr-2' %>
                    <% else %>
                      <%= image_tag "user avatar default.png", height:48, width:48, class: 'rounded-circle clickhand mr-2' %>
                    <% end %>
                    <%= member.username %>
                  </span>
                </li>
                <% end %>
              </ul>
            </div>

            <!-- Add tags -->
            <div class="dropdown mr-1">
              <label class="tag btn btn-light my-1" id="dLabel" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                <span><i class="fas fa-tags fa-sm"></i></span>
                <span class="tag-title">標籤</span>
              </label>
              <form class="tag-menu dropdown-menu text-center" aria-labelledby="dropdownMenuOffset">
                <h5 class="tag-header">建立新標籤</h5>
                <li class="tag-item form-group">
                  <div contenteditable="true" class="yellow-tag"></div>
                  <i id="add-tag" class="far fa-plus-square fa-sm btn"></i>
                </li>
                <li class="tag-item form-group">
                  <div contenteditable="true" class="blue-tag"></div>
                  <i id="add-tag" class="far fa-plus-square fa-sm btn"></i>
                </li>
                <li class="tag-item form-group">
                  <div contenteditable="true" class="green-tag"></div>
                  <i id="add-tag" class="far fa-plus-square fa-sm btn"></i>
                </li>
              </form>
            </div>

            <!-- Due date -->
            <div class="dropdown mr-1">
              <label class="datepicker btn btn-light my-1" d="dLabel" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="flase">
                <span><i class="far fa-clock fa-sm"></i></span>
                <span class="date-title">截止日</span>
              </label>
              <form class="date-form dropdown-menu">
                <input type="date" class="date-input form-control" placeholder="設定日期">
              </form>
            </div>

          </div>
        </div>
      </div>

      <div class="form-group d-flex justify-content-end">
        <button data-role="card-update" type="submit" class="card-update btn btn-info">儲存</button>
      </div>
    </div>
  </div>
</div>

app/views/boards/agree_invite.js.erb
if(<%= @reply %>){
  let inviteBoardCreate = `<ul class="team-boards">
                            <li>
                              <a class="card-body-public" href="/boards/<%= @board.id %>">
                                <span class="card-title">
                                  <%= @board.title %>
                                </span>
                              </a>
                            </li>
                          </ul>`
  $("#team-boards-container").append(inviteBoardCreate)
  $("#invite_<%= @invitation.id %>").remove()
  console.log(inviteBoardCreate)

}else{
  $("#invite_<%= @invitation.id %>").remove()
}

app/views/boards/index.html.erb
<%= render "boardcreate", board: @board %>

<% content_for :navbar do %>
<%= render 'shared/navbar' %>
<% end %>

<div class="container">

  <div class="row justify-content-center overview">
    <div class="col-8 col-sm-8">
      <div class="all-boards-container">
        <p class="board-title">
          <span class="fas fa-star"></span>
          我的最愛
        </p>
        <% @star_boards.each do |board| %>
          <ul class="starred-boards">
            <li>
              <%= link_to board_path(board.id), class: 'card-body-starred' do %>
              <span class="card-title">
                <%= board.title %>
              </span>
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>

      <div class="all-boards-container">
        <p class="board-title">
          <span class="fas fa-user-edit"></span>
          個人看板
        </p>
        <% @private_boards.each do |board| %>
          <ul class="personal-boards">
            <li>
              <%= link_to board_path(board.id), class: 'card-body-personal' do %>
              <span class="card-title">
                <%= board.title %>
              </span>
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>
      
      <div class="all-boards-container" id="team-boards-container">
        <p class="board-title">
          <span class="fas fa-users"></span>
          團隊看板
        </p>
        <% @public_boards.each do |board| %>
          <ul class="team-boards">
            <li>
              <%= link_to board_path(board.id), class: 'card-body-public' do %>
              <span class="card-title">
                <%= board.title %>
              </span>
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>

<div class="col-4 col-sm-4">
  <div class="create-board fab fa-flipboard d-flex justify-content-center">
    <p class="board-create">
      <a href="" class="btn new-board" data-toggle="modal" data-target="#createBoard">新增看板＋</a>
    </p>
  </div>

  <%#.. 邀請協作.. %>
    <div aria-live="polite" aria-atomic="true" class="invite-create-group mx-5">
        <% @searchuser.each do |invitation| %>
          <div class="toast" id="invite_<%= invitation.id %>" role="alert" data-autohide="false" aria-live="assertive"   aria-atomic="true">
            <div class="toast-header">
              <div class="welcome far fa-paper-plane">
                 <!-- <i class="far fa-paper-plane"></i> -->
                <div class="welcome-message">有人邀請您加入他的看板</div> 
              </div>
                <div class="invited-time">
                  <small class="js-invited-small"><%= invitation.created_at %></small>
                </div> 
              <div class="toast-body">
                <div class="invitation-message">
                  <%= invitation.message %>
                </div>
                <div class="answer">
                  <%= link_to "同意", agree_invite_boards_path(id: invitation.id, board_id:   invitation.board_id, agree: true), method: "put", remote: true, class:"btn btn-info btn-sm" %>
                <%= link_to '拒絕', agree_invite_boards_path(id: invitation.id, board_id:   invitation.board_id, agree: false), method: "put", remote: true, class:"btn btn-dark btn-sm" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
<%# ....%>

</div>

    </div>
  </div>
</div>

app/views/boards/searchuser.js.erb
$(".invite_controller").dropdown('toggle')
$("#navbarDropdown_email").val("")
$("#navbarDropdown_message").val("")

app/views/boards/show.html.erb
  <%= render "carditem" %>
  <% content_for :navbar do %>
    <%= render 'shared/navbar' %>
  <% end %>
  
  <% content_for :boardheader do %>
    <%= render 'shared/boardheader' %>
  <% end %>

<div data-role="js-list" class="list-container">
  <div class= "list-sortable" id="js-list-sortable">
  <% @lists.each do |list| %>
  <div data-role="list-group-item" class="list-group item"  id="list_<%= list.id %>">
    <div data-role="list-wrapper" class="list-wrapper">
      <div class='list-content box'>
        <div data-role= "list-item" class="list-item" >
          <input data-role="list-id" type="hidden" val= "<%= list.id %>">
          <span data-role="list-title" class="list-view"><%= list.title %></span>
          <div class="list-men">
            <span><i class="fas fa-align-justify"></i></span>
          </div>
        </div>
        
        <div data-role="card-wrapper" class="card-wrapper">

          <div data-role="card-group" class="card-group card-sortable">
            <div data-role="sort-able hidden" class="sortable-hidden"></div>
              <% list.cards.sorted.each do |card| %>
                <div data-role="sortable-column" class="cart-item" id= "<%= card.id %>">
                  <input data-role="card-id" type="hidden" val= "<%= card.id %>">
                  <span data-role="card-title" class="card-title-span"><%= card.title %></span>
                </div>
            <% end %>
          </div>

          <div class="card-input-controller">
            <div data-role="card-input" class="card-create input">
              <textarea class="card-create-area" name="card-text"></textarea>
            </div>

            <div data-role="card-btn" class="card-create btn">
              <button data-role="card-create-btn" class="card-add btn btn-success">送出</button>
              <span class="card-add-bot"><i class="list-cle fas fa-times"></i></span>
            </div>
          </div>

          <div class= "card-create-drop">
            <span class="card-create-span"><i class="card-add-i fas fa-plus"></i>新增卡片</span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

  <div data-role="input-local" class="list-group item" id="input-local">
    <div class="list-wrapper">
      <div class="list-position"></div>
      <div class="list-add-top" id="js-list-content-btn">
        <span class="list-add-span">
          <i class="list-add-i fas fa-plus"></i>新增列表
        </span>
      </div>
      <span class="list-add-form">
        <%= form_with model: @list, url: board_lists_path(@board), id: "js-list-from", class: "list-from" do |list| %>
          <%= list.text_field :title , class: "form-inp", data_role: "api-list-title", placeholder: "請輸入標題", maxlength: "100", autocomplete: "off"%>
          <div class="list-btn type">
            <%= list.submit "送出", class: "list-btn btn btn-success", data_role: "btn list-create" %>
            <span class="list-add-bot"><i class="fas fa-times"></i></span>
          </div>
      <% end %>
    </span>
    </div>
  </div>
</div>